name: Agent TODO

on:
  push:
    paths:
      - 'docs/**'
      - 'scripts/generate_todo.mjs'
      - '.github/workflows/agent-todo.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate TODO.md with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node ./scripts/generate_todo.mjs

      - name: Commit TODO.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add TODO.md
          git commit -m "chore: update TODO.md [skip ci]" || echo "No changes to commit"
          git push
